Handle shadow DOM
hinderlingvolkart/h123 pull request #5
Opened 2023-09-21 20:56 UTC by backflip

This PR updates the script to find headings in shadow DOM, too.

Additional changes:
- Elements with `role=["presentation"]` are ignored.
- Visibility is detected using `.offsetParent` rather than calculated styles.

2023-10-24 15:44 UTC, betabong requested changes
Hey @backflip thanks for taking the time! Please have a look at my line comment.

2023-10-24 15:44 UTC, betabong commented on src/bookmarklet.js
> +  return el.offsetParent !== null;
I'm fine with all changes except this one. Checking against offsetParent doesn't handle many cases of invisibility to the accessibility tree. Why have you removed the original code (does it have to do with shadow dom compatibility?)

2023-10-25 16:26 UTC, backflip commented on src/bookmarklet.js
> +  return el.offsetParent !== null;
@betabong, very good question! I had issues with slotted content and somehow forgot to follow up. This should be fixed now, the only remaining change in there is regarding the previous `el = el.parentElement`.

2023-10-25 16:45 UTC, merged

2023-10-25 16:45 UTC, betabong commented
Perfect, thanks for the contribution!